### PR TITLE
Fix empty ref scroll

### PR DESCRIPTION
**Pull request by Asgator**
setTimeout work afte componentWillUnount, and error 

> Cannot read property 'style' of undefined

Screenshot 2019-07-17 at 13 56 35
Screenshot 2019-07-17 at 13 56 48

### CODE REVIEW

**Comment by lanjingling0510** [comment]
@Asgator can you serve a demo about this error?

**Comment by Asgator** [comment]
@lanjingling0510 number scrolle and befor stop unmounted component 
In my situation that hestory go back;

**Comment by lanjingling0510** [comment]
@Asgator okay.  l will publish it in next version these days.

**Comment by Asgator** [comment]
@lanjingling0510 thank you

**Comment by AnZhiYu** [comment]
When will the version be released

**Pull request merged**
